[theme]
base = "light"
primaryColor = "#111111"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A0A0A"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
runOnSave = true
